version: "3.9"

services:
  crewai-agent-service:
    build:
      context: .
      target: production
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./logs:/app/logs
      - supervisor_run:/var/run/supervisor
    healthcheck:
      test: ["CMD-SHELL", "supervisorctl status crewai-agent | grep RUNNING || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  supervisor_run:
    driver: local
